spring.application.name=inventory

# PostgreSQL Config
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d78jr495pdvs73b3dmcg-a.oregon-postgres.render.com:5432/inventory_db_nbrk}
spring.datasource.username=inventory_db_nbrk_user
spring.datasource.password=zNtGDs5YofOIBzAm1mHW4zVEyfWwlyCP
#postgresql://inventory_db_nbrk_user:zNtGDs5YofOIBzAm1mHW4zVEyfWwlyCP@dpg-d78jr495pdvs73b3dmcg-a.oregon-postgres.render.com/inventory_db_nbrk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Initialize database
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:schema.sql

server.port=${SERVER_PORT:8084}

# Logging configuration
logging.level.root=INFO
logging.level.com.seproject.inventory=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

